#!/usr/bin/env ruby

require "rubygems"
require "nokogiri"
require "open-uri"

pages = ["http://webcache.googleusercontent.com/search?q=cache:blog.hungrymachine.com"]
2.upto(8).each do |n|
  pages << "http://webcache.googleusercontent.com/search?q=cache:blog.hungrymachine.com/page/#{n}/"
end

pages.each do |page|
  puts "Getting #{page}"
  index_page = Nokogiri::HTML(open(page))

  index_page.css('.post').each do |post|
    title = nil
    path = nil
    author = nil

    post.css('h2:first a').each do |link|
      title = link["title"]
      path = link["href"].sub("http://blog.hungrymachine.com", "").sub(/\/$/,'')
    end

    metadata = post.at_css('.postmetadata')
    if metadata.inner_html =~ /by ([^,]+),/
      author = $1
    else
      puts "NO AUTHOR!"
    end

    entry = post.at_css('.entry')
    file_name = File.expand_path(File.join(File.dirname(__FILE__), "../_posts", "#{path.gsub("/","-").sub(/^-|-$/,'')}.html"))
    puts "Saving #{file_name}"
    open(file_name, "w") do |f|
      f << %{---
layout: post
title: #{title}
author: #{author}
---
      }
      f << entry.inner_html
    end
  end
end